name: lint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: |
        sudo apt-get install -y libkrb5-dev
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Test with tox
      run: tox -v -e pep8
