name: lint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: sudo apt-get install -y libkrb5-dev

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Test
      run: uv run flake8 grafana_dashboards tests
