name: Type Check
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  mypy:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: libkrb5-dev
          version: 1.0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run mypy
        run: uv run mypy .
